stages:
  - build
  - deploy
  - enable_merge

build_job:
  stage: build
  tags: 
    - tomhp
  script:
    ./debBuild.sh
  artifacts:
    paths:
      - ./build_deb/  
  only:
    - embtom-1.10.0

deploy_job:
  stage: deploy
  tags: 
    - tomhp
  script:
    - cd ./build_deb
    - cp * /media/volume1/ci_projects/snapshot/googletest
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic googletest
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic google-mock
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic googletest-tools
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic libgmock-dev
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic libgtest-dev
    - reprepro -b /media/volume1/reprepo/ -A source remove bionic googletest
    - reprepro --ignore=wrongdistribution -b /media/volume1/reprepo/ -V include bionic googletest_1.10.0.20191003-1_amd64.changes
  when: on_success
  only:
    - embtom-1.10.0

enable_merge:
  stage: enable_merge    
  tags: 
    - tomhp
  script:
    - ./debBuild.sh
  only: 
    - merge_requests




